name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Stable
        run: cargo test
      - name: Stable (no default features)
        run: cargo test -p alacritty_terminal --no-default-features
      - name: Oldstable
        run: |
          rustup default $(cat alacritty/Cargo.toml | grep "rust-version" | sed 's/.*"\(.*\)".*/\1/')
          cargo test
      - name: Clippy
        run: |
          rustup component add clippy
          cargo clippy --all-targets

          
  check-macos-x86_64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install target
        run: rustup update && rustup target add x86_64-apple-darwin
      - name: Build
        run: cargo build --target=x86_64-apple-darwin
        
  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: brew install scdoc
      - name: Install ARM target
        run: rustup update && rustup target add aarch64-apple-darwin && rustup target add x86_64-apple-darwin
      - name: Test
        run: cargo test --release --target=x86_64-apple-darwin
      - name: Build ARM
        run: cargo build --release --target=aarch64-apple-darwin
      - name: Make DMG
        run: make dmg-universal
      - name: Upload to Artifacts 
        uses: actions/upload-artifact@v4 
        with: 
          name: Artifacts 
          path: ./target/release/osx/Alacritty.dmg

